// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArquivosDocumentDataSlicesSlice = never;

/**
 * Content for Arquivos documents
 */
interface ArquivosDocumentData {
  /**
   * Calendário Acadêmico field in *Arquivos*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Calendário Acadêmico
   * - **API ID Path**: arquivos.calendario_academico
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calendario_academico: prismic.LinkToMediaField;

  /**
   * Regulamento Institucional field in *Arquivos*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Regulamento Institucional
   * - **API ID Path**: arquivos.regulamento_institucional
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  regulamento_institucional: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Arquivos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: arquivos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArquivosDocumentDataSlicesSlice> /**
   * Meta Title field in *Arquivos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: arquivos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Arquivos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: arquivos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Arquivos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: arquivos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Arquivos document from Prismic
 *
 * - **API ID**: `arquivos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArquivosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArquivosDocumentData>,
    "arquivos",
    Lang
  >;

type CoursesDocumentDataSlicesSlice = never;

/**
 * Content for Courses documents
 */
interface CoursesDocumentData {
  /**
   * Course Banner field in *Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Nome do Curso field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do Curso
   * - **API ID Path**: courses.curso
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  curso: prismic.KeyTextField;

  /**
   * Descrição field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Descrição do Curso
   * - **API ID Path**: courses.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Descrição Extensa field in *Courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição detalhada
   * - **API ID Path**: courses.descricao_extensa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_extensa: prismic.RichTextField;

  /**
   * Mercado de Trabalho field in *Courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Mercado de Trabalho
   * - **API ID Path**: courses.mercado_de_trabalho
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mercado_de_trabalho: prismic.RichTextField;

  /**
   * Infraestrutura field in *Courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Infraestrutura
   * - **API ID Path**: courses.infraestrutura
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  infraestrutura: prismic.RichTextField;

  /**
   * Disiplinas field in *Courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Disciplinas
   * - **API ID Path**: courses.disiplinas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disiplinas: prismic.RichTextField;

  /**
   * Semestres field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Semestres
   * - **API ID Path**: courses.semestres
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  semestres: prismic.KeyTextField;

  /**
   * Modalidade field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Modalidade
   * - **API ID Path**: courses.modalidade
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modalidade: prismic.KeyTextField;

  /**
   * Slice Zone field in *Courses*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoursesDocumentDataSlicesSlice> /**
   * Meta Title field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: courses.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: courses.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoursesDocumentData>,
    "courses",
    Lang
  >;

type PostsDocumentDataSlicesSlice = never;

/**
 * Content for Posts documents
 */
interface PostsDocumentData {
  /**
   * Image field in *Posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Author field in *Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Slice Zone field in *Posts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostsDocumentDataSlicesSlice>;
}

/**
 * Posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostsDocumentData>, "posts", Lang>;

export type AllDocumentTypes =
  | ArquivosDocument
  | CoursesDocument
  | PostsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArquivosDocument,
      ArquivosDocumentData,
      ArquivosDocumentDataSlicesSlice,
      CoursesDocument,
      CoursesDocumentData,
      CoursesDocumentDataSlicesSlice,
      PostsDocument,
      PostsDocumentData,
      PostsDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
